# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [1]:
import numpy

a = numpy.full((6, 4), 2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [9]:
import numpy

b = numpy.full((6, 4), 1)
numpy.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [16]:
print(a * b)
# print(numpy.dot(a, b))
# a * b works because all elements in the same position across a and b are multiplied.
# dot(a, b) doesn't work because this does matrix multiplication, where the columns of the first column must match the rows of the second column.

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 4

In [24]:
c = numpy.dot(a.transpose(), b)
d = numpy.dot(a, b.transpose())
print(c.shape)
print(d.shape)

# These are different shapes because transpose switches the dimensions of the array.
# Furthermore, the shape of the dot product of two matrices is the column count of the first array, and the row count of the second array.
# a.transpose() has four columns, b has four rows.
# a has six columns, b.transpose() has six rows.

(4, 4)
(6, 6)


## Exercise 5

In [25]:
print("Some output on the screen")

Some output on the screen


## Exercise 6

In [38]:
x = numpy.random.rand(6, 4)
y = numpy.random.rand(6, 4)
z = numpy.random.rand(6, 4)

print(numpy.sum(x))
print(numpy.sum(y))
print(numpy.sum(z))

print(numpy.mean(x))
print(numpy.mean(y))
print(numpy.mean(z))

print(numpy.sum((x, y, z)))
print(numpy.mean((x, y, z)))

12.64287694237581
14.566892922540022
12.16156192549519
0.5267865392656588
0.6069538717725009
0.5067317468956329
39.37133179041103
0.5468240526445975


## Exercise 7

In [55]:

def slowLoopThrough2DArray(arr):
    count = 0
    for x in range(arr.shape[0]):
        for y in range(arr.shape[1]):
            if(arr[x][y] == 1):
                count+=1
    return(count)

def fastLoopThrough2DArray(arr):
    count = 0
    spots = numpy.where(arr == 1)
    return(len(spots[0]))

arr = numpy.eye(3)
count = 0
count = slowLoopThrough2DArray(arr)
print(count)
count = fastLoopThrough2DArray(arr)
print(count)

3
3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE